- primed/cdsa/tables.py
- primed/cdsa/tests/test_tables.py
- primed/dbgap/tables.py
- primed/dbgap/tests/test_tables.py
- primed/primed_anvil/tables.py
- primed/primed_anvil/tests/test_tables.py
- requirements/local.txt
- Add default order_by to the tables in the `primed_anvil`, `dbgap`, and `cdsa` apps.
This makes it easier for users to find what they're looking for, compared to when tables were just sorted by pk.
Closes #227
> Sort tables alphabetically

- primed/dbgap/tables.py
- primed/dbgap/tests/test_tables.py
- primed/templates/dbgap/dbgapdataaccesssnapshot_detail.html
- Use short names for columns
- Remove columns
- Show only workspace name instead of billing project + name
- Smaller bootstrap/html formatting
> Make the dbGaP DAR table more compact

- config/settings/base.py
- primed/dbgap/tables.py
- primed/dbgap/tests/test_views.py
- primed/dbgap/urls.py
- primed/dbgap/views.py
- primed/templates/dbgap/dbgapapplication_records.html
- primed/templates/dbgap/records_index.html
These records pages are similar to the CDSA records.
- Add a records index page
- Add a dbGaP applications records page
Closes #262
> Add a public dbGaP records page

- .github/workflows/ci.yml
Since we're not running 10.3 anymore, we don't need to test against it in CI.
> Remove MariaDB 10.3 from CI

- requirements/dev-requirements.in
- requirements/dev-requirements.txt
- requirements/requirements.in
- requirements/requirements.txt
- requirements/test-requirements.in
Remove packages that are not actually being used. This will cut down on dependabot noise.
> Remove unused dependencies

- requirements/requirements.in
- requirements/requirements.txt
Necessary for logging in via the admin interface.
> Add argon2-cffi back to requirements

- config/settings/base.py
- primed/cdsa/adapters.py
- primed/cdsa/tables.py
- primed/cdsa/tests/test_tables.py
- primed/dbgap/adapters.py
- primed/dbgap/tables.py
- primed/dbgap/tests/test_tables.py
- primed/dbgap/tests/test_views.py
- primed/dbgap/views.py
- primed/duo/tests/test_views.py
- primed/duo/views.py
- primed/miscellaneous_workspaces/adapters.py
- primed/miscellaneous_workspaces/tables.py
- primed/miscellaneous_workspaces/tests/test_tables.py
- primed/primed_anvil/tables.py
- primed/primed_anvil/tests/test_views.py
- primed/primed_anvil/views.py
- primed/templates/base.html
- primed/templates/duo/datausemodifier_detail.html
- primed/templates/duo/datausepermission_detail.html
- primed/templates/pages/home.html
- requirements/requirements.in
- requirements/requirements.txt
- Update to ACM v0.21. This opens some views up to users with AnVILConsortiumManagerView permission.
- Open DUO views to anyone who with AnVILConsortiumManagerView (so essentially anyone who has logged in)
- Update home page for above changes
- Show an alert to users who have not linked their accounts
Closes #328
> Update to ACM v0.21 and open more views to logged in users

- .gitleaksignore
These fingerprints and secrets in this file are no longer used, but they keep getting detected by periodic gitleaks scans. As a temporary workaround until we can remove them from the repo history, create this file so gitleaks detect stops flagging these every time it runs.
> Add gitleaksignore file

- .github/dependabot.yml
- Run dependabot weekly
- Allow more than the default number of pull requests
- Run dependabot on both direct and indirect dependencies (may not matter with pip-tools)
> Dependabot updates, now branched off of main

- requirements/requirements.in
- requirements/requirements.txt
This update fixes a bug where the permissions of the maintenance mode state file are not properly maintained (due to the implementation in python-fsutil). v0.21.1 of django maintenance mode requires the version of python-fsutil where this bug is fixed. See fabiocaccamo/django-maintenance-mode#172 for info.
> Update to latest version of django-maintenance-mode

- primed/dbgap/tests/test_views.py
- primed/templates/dbgap/dbgapworkspace_detail.html
Regular view users cannot access the dbGaP workspace audit page, so only show that link to staff users.
> Hide dbGaP audit link from view users

- primed/dbgap/tables.py
- primed/dbgap/tests/test_tables.py
- primed/dbgap/tests/test_views.py
- primed/dbgap/urls.py
- primed/dbgap/views.py
- primed/templates/dbgap/dbgapdataaccessrequest_history.html
- primed/templates/dbgap/dbgapdataaccessrequest_list.html
- primed/templates/dbgap/nav_items.html
> Add a view showing history for a DAR

- .gitignore
- add_dbgap_example_data.py
- primed/collaborative_analysis/tests/factories.py
- primed/dbgap/audit.py
- primed/dbgap/tests/factories.py
- primed/dbgap/tests/test_audit.py
- primed/dbgap/tests/test_views.py
- primed/dbgap/urls.py
- primed/dbgap/views.py
- primed/templates/dbgap/dbgap_audit.html
- primed/templates/dbgap/nav_items.html
Add a view to do a "full" audit of dbGaP access, which audits access to all dbGaPWorkspaces for all dbGaPApplications.
- Refactor dbGaP auditing classes to use only one class without duplicated code.
- Add a new view to audit all application/workspace combos.
> Add view to audit all dbGaP Applications and Workspaces at the same time

- .github/workflows/ci.yml
- primed/cdsa/tests/test_commands.py
- primed/cdsa/tests/test_views.py
- primed/cdsa/views.py
- primed/dbgap/views.py
- primed/duo/management/commands/load_duo.py
- primed/primed_anvil/tests/test_helpers.py
- primed/primed_anvil/views.py
- pytest.ini
Convert all warnings to errors when running pytest. This should help catch DeprecationErrors that are raised in dependabot updates.
As part of this, add some additional filters to the pytest file to ignore warnings that we don't have control over (e.g., those raised by third-party packages).
> Convert pytest warnings to errors

- primed/cdsa/audit/signed_agreement_audit.py
- primed/cdsa/audit/workspace_audit.py
- primed/cdsa/tests/test_audit.py
Similar to updates for the dbGaP audit, allow the CDSA audit classes to take the queryset of objects to run on as an input.
> Add input querysets to CDSA audits

- primed/cdsa/tables.py
- primed/dbgap/tables.py
- primed/primed_anvil/tables.py
- primed/primed_anvil/tests/test_tables.py
- primed/templates/cdsa/cdsaworkspace_detail.html
- primed/templates/dbgap/dbgapworkspace_detail.html
- primed/templates/snippets/gsr_restricted_badge.html
- Update BooleanIconColumn to allow the user to specify the Bootstrap icon and the color to color it
- Use a yellow color with a dash/minus icon for the gsr_restricted columns in workspace list tables
- Change the icon for gsr_restricted on detail pages to match the icon in the columns
- Move the gsr_posting_restricted badge into its own snippet
> Change the appearance of the gsr_restricted field on the site

- primed/cdsa/management/commands/cdsa_records.py
- primed/cdsa/tests/test_commands.py
- primed_apps.cron
- primed_apps_dev.cron
- Modify the cdsa_records command to accept --outdir as a keyword argument instead of as a positional argument
> Add a cron job for generating CDSA records

- .github/dependabot.yml
I think this is ok since dependencies are handled by pip-sync?
> Try allowing only "direct" dependency types

- .github/dependabot.yml
- .github/workflows/combine-prs.yml
Dependabot grouped updates were not ideal, since it didn't run CI first. Instead, use the github/combine-prs action, which only combines PRs after CI has passed.
> Combine Dependabot PRs using combine-prs

- .github/dependabot.yml
As before, dependabot was timing out.
> Use only direct dependencies

- config/settings/base.py
- primed/primed_anvil/tests/test_views.py
- primed/static/css/project.css
- primed/templates/base.html
- requirements/requirements.in
- requirements/requirements.txt
- Use the django-constance app to add settings that can be edited in the admin
- Add a SITE_ANNOUNCEMENT setting
- If SITE_ANNOUNCEMENT is non-blank, show an alert with the text of the site announcement
> Add ability to show banner announcements

- primed/static/js/project.js
In form input fields with the maxlength attribute, add custom javascript that prevents pasting text with more than maxlength characters. This can help prevent data truncation when pasting more characters than maxlength allows, since by default they would be silently truncated.
Closes #491
> Check copy-paste text in form fields and alert if it exceeds maxlength

- primed/cdsa/adapters.py
- primed/cdsa/tables.py
- primed/cdsa/tests/test_views.py
- primed/collaborative_analysis/tables.py
- primed/dbgap/adapters.py
- primed/dbgap/tables.py
- primed/dbgap/tests/test_views.py
- primed/miscellaneous_workspaces/adapters.py
- primed/miscellaneous_workspaces/tables.py
- primed/miscellaneous_workspaces/tests/test_tables.py
- primed/primed_anvil/tables.py
- primed/templates/snippets/data_prep_workspace_table.html
- Subclass the user table to create the staff tables, and modify columns as necessary. This reduces duplication of code.
- Do not show associated data prep workspace tables to regular view users on the dbGaP and CDSA workspace detail pages.
Closes #524
> Consolidate definitions for staff and user tables

- primed/primed_anvil/helpers.py
- primed/primed_anvil/tests/test_helpers.py
- primed/primed_anvil/tests/test_views.py
> Show CDSA workspaces in data summary view

- .github/workflows/ci.yml
- README.md
The pre-commit action recommends using pre-commit.ci instead.
Note: before starting this PR, I gave pre-commit ci access to this repo starting at this page:
https://results.pre-commit.ci/
> Use pre-commit.ci

- .pre-commit-config.yaml
- add_phenotype_inventory_input_example_data.py
- primed/primed_anvil/helpers.py
- primed/primed_anvil/tests/test_helpers.py
- primed/primed_anvil/tests/test_views.py
- primed/primed_anvil/urls.py
- primed/primed_anvil/views.py
- primed/static/js/project.js
- primed/templates/primed_anvil/phenotype_inventory_inputs.html
This PR is part of a bigger project in PRIMED to create a phenotype inventory in AnVIL. A workflow already exists to create the inventory using a list of workspaces and associated studies (see https://github.com/UW-GAC/primed-inventory-workflows), and this PR generates the input for that workflow.
- Add a helper function that prepares the input for the workflow.
- Add a view to display the input and allow the user to copy it to the clipboard.
> Generate input for the phenotype inventory workflow

- requirements/dev-requirements.in
dependabot tried to update to django-stubs 5.0, but we are running django 4.2.
> Pin django-stubs to a matching django version

- pytest.ini
Add the `-n auto` setting to pytest `addopts` in pytest.ini file
> Run parallelized pytest tests by default

- .github/workflows/ci.yml
* Add a step to the CI that (optionally) reruns pip-compile on the requirements.in files
* Add a pip-recompile setting to the matrix definitions that can be used to toggle whether this step should run.
The pip-recompile setting can be set to true when we want to test future versions of python compared to what is running on the live servers.
> Add a CI step to optionally recompile requirements files with pip-sync

- .github/workflows/ci.yml
- primed/drupal_oauth_provider/tests.py
- pytest.ini
- requirements/requirements.in
- requirements/requirements.txt
- Use python 3.12 in future CI
- Fix a deprecation warning in `drupal_oauth_provider`
> Switch future CI to use python 3.12

- .github/workflows/pip-compile.yml
Add a new workflow for pull requests into main that:
* compiles the requirements files
* opens a pull request if changes are detected
* exits successfully (if no changes are detected) or unsuccessfully (if changes are detected)
> Set up CI to run pip-compile, check for changes, and open a pull request

- add_cdsa_example_data.py
- add_dbgap_example_data.py
- primed/cdsa/tests/test_views.py
- primed/dbgap/tests/test_views.py
- primed/dbgap/views.py
- primed/templates/cdsa/dataaffiliateagreement_detail.html
- primed/templates/cdsa/memberagreement_detail.html
- primed/templates/cdsa/nondataaffiliateagreement_detail.html
- primed/templates/dbgap/dbgapapplication_detail.html
- primed/templates/dbgap/dbgapapplication_update_collaborators.html
- primed/templates/users/user_detail.html
- primed/users/tests/test_views.py
- primed/users/views.py
- Show similar information on the templates for dbGaP and CDSA collaborator/accessor/uploader update views.
- Add button to dbGaPApplicationDetail to update collaborators.
> Harmonize dbgap and cdsa updates

- primed/primed_anvil/filters.py
- primed/primed_anvil/tests/test_views.py
- primed/primed_anvil/views.py
- primed/templates/primed_anvil/study_list.html
Define StudyListFilter
Add StudyListFilter to StudyList view
Add search boxes for short name and full name in StudyList view
> Add search to Study List

- primed/templates/users/user_detail.html
The user detail template was still printing out the signed agreements from when I was trying to debug something. Remove that statement.
> Remove debugging print statement in template

- primed/collaborative_analysis/tests/test_views.py
- primed/primed_anvil/forms.py
- primed/primed_anvil/tests/test_forms.py
In the WorkspaceAuthDomainDisabledForm, check if authorization_domains is actually a field before attempting to set it to disabled. Before this fix, attempting to set it to disabled was causing an error in the ACM WorkspaceUpdate view, because that view removed some of the fields that can't be changed after creation, including the authorzations_domains field. Add tests to catch this case.
> Fix bug with WorkspaceAuthDomainDisabledForm and WorkspaceUpdate view

- primed/primed_anvil/tests/test_views.py
- primed/primed_anvil/views.py
The UserAccountTable on the StudySite detail page was showing inactive users. Hide the users in the queryset and add a test for this case.
Closes #651
> Hide inactive users in study site table

- primed/dbgap/tests/test_forms.py
test_dbgap_project_id_does_not_match was failing only in mysql likely because in mysql tests, the pk field does not reset to 1 for each test. A (new) previous test likely created a dbGaP application, so when this test had the project_id hard-coded, it failed. Now, set the dbGaP application project_id using the application that the test created in the setup method.
> Fix failing test for mysql

- primed/templates/primed_anvil/studysite_detail.html
The badge next to the consortium members with data access is using the wrong table; use the correct table to calculate the count to show in the badge.
> Fix badge for consortium members with data access

- primed/templates/base.html
- primed/templates/users/user_detail.html
- primed/users/forms.py
- primed/users/tests/test_forms.py
- primed/users/tests/test_views.py
- primed/users/views.py
- Show alerts on the user profile page if 1) the user is inactive or 2) the user's linked account is inactive
- Hide inactive users in the user autocomplete view
- Do not allow user lookups for inactive users (but you can still manually navigate to their profile page)
and a couple other misc updates:
- make the alert about linking your account dismissible
> Better behavior for inactive users

- add_inventory_input_example_data.py
- primed/primed_anvil/helpers.py
- primed/primed_anvil/tests/test_helpers.py
- primed/primed_anvil/tests/test_views.py
- primed/primed_anvil/urls.py
- primed/primed_anvil/views.py
- primed/templates/anvil_consortium_manager/navbar.html
- primed/templates/primed_anvil/inventory_inputs.html
We've found a bug associated with the inventory inputs view/helper. In some cases, only one study is shown when a workspace is associated with multiple studies.
From inspecting prod data, it seems to occur when there are multiple workspaces associated with more than 1 study, and those workspaces are not listed in consecutive order when calling `itertools.groupby`.
Note that I was unable to get the new test to fail in CI, but from manual testing on the staging server, this appears to fix the issue.
Closes #675
> Fix bug where only a single study is shown for a workspace linked to multiple studies

- primed/cdsa/views.py
- primed/dbgap/views.py
- primed/primed_anvil/tables.py
- primed/primed_anvil/views.py
- primed/templates/primed_anvil/studysite_detail.html
- Change the default verbose name of the `is_group_member` column from`UserAccountSingleGroupMembershipTable`
- Change the column name dynamically to an appropriate value in views (e.g., "in access group", "in upload group", etc.)
- Update wording on the StudySiteDetail template
Closes #673
> Clarify "has access" in study site member table

- .github/dependabot.yml
Since we're now using the action to combine dependabot PRs into a single PR, it's ok if dependabot runs more frequently.
> Run dependabot nightly

- .github/workflows/pip-compile.yml
This should(?) allow the create-pull-request action to run and create a PR on dependabot updates. (This mostly affects security updates?)
> Add permissions for pip-compile workflow

- config/settings/base.py
- primed/primed_anvil/adapters.py
- primed/primed_anvil/tests/test_adapters.py
- primed/primed_anvil/tests/test_views.py
This adapter automatically adds the CC ADMINS group to any group created by the app via the ManagedGroupCreate view.
> Add a custom ManagedGroupAdapter

- primed/primed_anvil/adapters.py
- primed/primed_anvil/tests/test_adapters.py
- Add an adapter method to automatically share a workspace with the CC admin group after import
> Automatically share workspaces with admin group after import

- .github/workflows/combine-prs.yml
It is better to review the dependabot PRs, close any that we do not want included in the combined update, and then run the combine-prs workflow manually (via workflow dispatch). This way we won't inadvertently get updates that we don't want (e.g., a passing PR that updates to django-5.0).
> Do not schedule combine-prs workflow

- primed/cdsa/tests/factories.py
- primed/primed_anvil/tests/factories.py
This should eliminate errors due to accidentally creaitng or trying to create a new instance with the same value as another object that already exists.
> Use Sequence for unique model fields in factories

- primed/primed_anvil/views.py
They caused the view to only display 10 studies instead of the default 25, and were unnecessary - hey were either leftover from some other view or accidentally added.
> Remove extra/unused classes in StudyList view

- .github/workflows/ci.yml
- .github/workflows/gitleaks.yml
- .github/workflows/pip-compile.yml
- pin all actions to their latest version, so updates can be handled by dependabot
- fix coverage steps so that it works with the latest version of github actions' upload-artifact (which includes a breaking change to not upload hidden files)
> Fix CI for upload artifact breaking change

- .github/workflows/pip-compile.yml
Paths in the requirements.txt file get converted to absolute paths instead of relative paths. This can (temporarily?) be fixed by pinning pip to a specific version. Hopefully?
> Fix absolute paths in requirements files with latest version of pip and pip-compile

- primed/primed_anvil/adapters.py
Add a custom message after a user links their account that indicates that data access is not immediate.
> Custom message after account link

- primed/primed_anvil/adapters.py
I had accidentally changed this to a test email when moving the settings and forgotten to change it back, so we were missing email notifications since b27ff1c3.
> Switch account_verify_notification_email back to correct email
